/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author isaqu
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
 
    Color DefaultColor, ClickColor;
    
    
    public Dashboard() {
        initComponents();
        DefaultColor= new Color(13,36,70);
        ClickColor = new Color(220,141,77);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        homeBut = new javax.swing.JPanel();
        homeTxt = new javax.swing.JLabel();
        atividadesBut = new javax.swing.JPanel();
        homeTxt1 = new javax.swing.JLabel();
        cadastrarBut = new javax.swing.JPanel();
        homeTxt2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(2, 31, 54));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeBut.setBackground(new java.awt.Color(2, 31, 54));
        homeBut.setToolTipText("Home");
        homeBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButMouseExited(evt);
            }
        });

        homeTxt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homeTxt.setForeground(new java.awt.Color(255, 255, 255));
        homeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTxt.setText("Home");

        javax.swing.GroupLayout homeButLayout = new javax.swing.GroupLayout(homeBut);
        homeBut.setLayout(homeButLayout);
        homeButLayout.setHorizontalGroup(
            homeButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        homeButLayout.setVerticalGroup(
            homeButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(homeTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(homeBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, -1));

        atividadesBut.setBackground(new java.awt.Color(2, 31, 54));
        atividadesBut.setToolTipText("Home");
        atividadesBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atividadesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atividadesButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atividadesButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atividadesButMouseExited(evt);
            }
        });

        homeTxt1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homeTxt1.setForeground(new java.awt.Color(255, 255, 255));
        homeTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTxt1.setText("Atividades");

        javax.swing.GroupLayout atividadesButLayout = new javax.swing.GroupLayout(atividadesBut);
        atividadesBut.setLayout(atividadesButLayout);
        atividadesButLayout.setHorizontalGroup(
            atividadesButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        atividadesButLayout.setVerticalGroup(
            atividadesButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atividadesButLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(homeTxt1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.add(atividadesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, -1));

        cadastrarBut.setBackground(new java.awt.Color(2, 31, 54));
        cadastrarBut.setToolTipText("Home");
        cadastrarBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarButMouseExited(evt);
            }
        });

        homeTxt2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homeTxt2.setForeground(new java.awt.Color(255, 255, 255));
        homeTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTxt2.setText("Cadastrar");

        javax.swing.GroupLayout cadastrarButLayout = new javax.swing.GroupLayout(cadastrarBut);
        cadastrarBut.setLayout(cadastrarButLayout);
        cadastrarButLayout.setHorizontalGroup(
            cadastrarButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeTxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        cadastrarButLayout.setVerticalGroup(
            cadastrarButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarButLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(homeTxt2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.add(cadastrarBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem-Vindo!");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 730));

        jDesktopPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanel3.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atividadesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atividadesButMouseClicked
    /* rota errada dashbord chamando cadastro de atividades
        /* AtividadesCadastradas atividadecadastrada = new AtividadesCadastradas();
      jDesktopPanel.removeAll();
      jDesktopPanel.add( atividadecadastrada).setVisible(true);*/
    }//GEN-LAST:event_atividadesButMouseClicked

    private void atividadesButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atividadesButMouseEntered
        atividadesBut.setBackground(new java.awt.Color(2,65,75));
    }//GEN-LAST:event_atividadesButMouseEntered

    private void atividadesButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atividadesButMouseExited
        atividadesBut.setBackground(new java.awt.Color(2,31,54));
    }//GEN-LAST:event_atividadesButMouseExited

    private void cadastrarButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseClicked
        TiposDeCadastro tipoDeCadastro = new TiposDeCadastro(jDesktopPanel);
        jDesktopPanel.removeAll();
        jDesktopPanel.add(tipoDeCadastro).setVisible(true);
    }//GEN-LAST:event_cadastrarButMouseClicked

    private void cadastrarButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseEntered
        cadastrarBut.setBackground(new java.awt.Color(2,65,75));
    }//GEN-LAST:event_cadastrarButMouseEntered

    private void cadastrarButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseExited
        cadastrarBut.setBackground(new java.awt.Color(2,31,54));
    }//GEN-LAST:event_cadastrarButMouseExited

    private void homeButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseExited
        homeBut.setBackground(new java.awt.Color(2,31,54));
    }//GEN-LAST:event_homeButMouseExited

    private void homeButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseEntered
        homeBut.setBackground(new java.awt.Color(2,65,75));
    }//GEN-LAST:event_homeButMouseEntered

    private void homeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseClicked

    }//GEN-LAST:event_homeButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atividadesBut;
    private javax.swing.JPanel cadastrarBut;
    private javax.swing.JPanel homeBut;
    private javax.swing.JLabel homeTxt;
    private javax.swing.JLabel homeTxt1;
    private javax.swing.JLabel homeTxt2;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
