/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author DELL
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aba = new javax.swing.JPanel();
        bemVinda = new javax.swing.JLabel();
        homeBut = new javax.swing.JPanel();
        homeTxt = new javax.swing.JLabel();
        atividadesBut = new javax.swing.JPanel();
        homeTxt1 = new javax.swing.JLabel();
        cadastrarBut = new javax.swing.JPanel();
        homeTxt2 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        atividades = new javax.swing.JPanel();
        cadastrar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addTurma1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addAluno = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addAtividades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aba.setBackground(new java.awt.Color(2, 31, 54));

        bemVinda.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        bemVinda.setForeground(new java.awt.Color(255, 255, 255));
        bemVinda.setText("Bem Vinda!");

        homeBut.setBackground(new java.awt.Color(2, 31, 54));
        homeBut.setToolTipText("Home");
        homeBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButMouseExited(evt);
            }
        });

        homeTxt.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homeTxt.setForeground(new java.awt.Color(255, 255, 255));
        homeTxt.setText("Home");

        javax.swing.GroupLayout homeButLayout = new javax.swing.GroupLayout(homeBut);
        homeBut.setLayout(homeButLayout);
        homeButLayout.setHorizontalGroup(
            homeButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeButLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeTxt)
                .addGap(124, 124, 124))
        );
        homeButLayout.setVerticalGroup(
            homeButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(homeTxt)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        atividadesBut.setBackground(new java.awt.Color(2, 31, 54));
        atividadesBut.setToolTipText("Home");
        atividadesBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atividadesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atividadesButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atividadesButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atividadesButMouseExited(evt);
            }
        });

        homeTxt1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homeTxt1.setForeground(new java.awt.Color(255, 255, 255));
        homeTxt1.setText("Atividades");

        javax.swing.GroupLayout atividadesButLayout = new javax.swing.GroupLayout(atividadesBut);
        atividadesBut.setLayout(atividadesButLayout);
        atividadesButLayout.setHorizontalGroup(
            atividadesButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atividadesButLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(homeTxt1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        atividadesButLayout.setVerticalGroup(
            atividadesButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atividadesButLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(homeTxt1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        cadastrarBut.setBackground(new java.awt.Color(2, 31, 54));
        cadastrarBut.setToolTipText("Home");
        cadastrarBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarButMouseExited(evt);
            }
        });

        homeTxt2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        homeTxt2.setForeground(new java.awt.Color(255, 255, 255));
        homeTxt2.setText("Cadastrar");

        javax.swing.GroupLayout cadastrarButLayout = new javax.swing.GroupLayout(cadastrarBut);
        cadastrarBut.setLayout(cadastrarButLayout);
        cadastrarButLayout.setHorizontalGroup(
            cadastrarButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarButLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(homeTxt2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadastrarButLayout.setVerticalGroup(
            cadastrarButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarButLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(homeTxt2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abaLayout = new javax.swing.GroupLayout(aba);
        aba.setLayout(abaLayout);
        abaLayout.setHorizontalGroup(
            abaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(bemVinda)
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(homeBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(atividadesBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cadastrarBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        abaLayout.setVerticalGroup(
            abaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bemVinda)
                .addGap(87, 87, 87)
                .addComponent(homeBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(atividadesBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(cadastrarBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        getContentPane().add(aba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 720));

        atividades.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout atividadesLayout = new javax.swing.GroupLayout(atividades);
        atividades.setLayout(atividadesLayout);
        atividadesLayout.setHorizontalGroup(
            atividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        atividadesLayout.setVerticalGroup(
            atividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(atividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 720));

        cadastrar.setBackground(new java.awt.Color(255, 51, 51));
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });

        addTurma1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26)); // NOI18N
        addTurma1.setText("Adicionar Turma");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(addTurma1)
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        addAluno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26)); // NOI18N
        addAluno.setText("Adicionar Aluno");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(addAluno)
                .addGap(148, 148, 148))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        addAtividades.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26)); // NOI18N
        addAtividades.setText("Adicionar Atividdes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(addAtividades)
                .addGap(129, 129, 129))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cadastrarLayout = new javax.swing.GroupLayout(cadastrar);
        cadastrar.setLayout(cadastrarLayout);
        cadastrarLayout.setHorizontalGroup(
            cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        cadastrarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel3, jPanel4});

        cadastrarLayout.setVerticalGroup(
            cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        getContentPane().add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarMouseClicked
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        CadastroAlunos cadastroalunos = new CadastroAlunos();
        cadastrar.removeAll();
        cadastrar.add(cadastroalunos).setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked
    
    private void homeButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseEntered
        homeBut.setBackground(new java.awt.Color(2,65,75));
    }//GEN-LAST:event_homeButMouseEntered

    private void homeButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseExited
        homeBut.setBackground(new java.awt.Color(2,31,54));
    }//GEN-LAST:event_homeButMouseExited

    private void homeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseClicked
        cadastrar.setVisible(false);
        atividades.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_homeButMouseClicked

    private void atividadesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atividadesButMouseClicked
        cadastrar.setVisible(false);
        atividades.setVisible(true);
        home.setVisible(false);
    }//GEN-LAST:event_atividadesButMouseClicked

    private void atividadesButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atividadesButMouseEntered
       atividadesBut.setBackground(new java.awt.Color(2,65,75));
    }//GEN-LAST:event_atividadesButMouseEntered

    private void atividadesButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atividadesButMouseExited
       atividadesBut.setBackground(new java.awt.Color(2,31,54));
    }//GEN-LAST:event_atividadesButMouseExited

    private void cadastrarButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseClicked
        cadastrar.setVisible(true);
        atividades.setVisible(false);
        home.setVisible(false);
    }//GEN-LAST:event_cadastrarButMouseClicked

    private void cadastrarButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseEntered
        cadastrarBut.setBackground(new java.awt.Color(2,65,75));
    }//GEN-LAST:event_cadastrarButMouseEntered

    private void cadastrarButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButMouseExited
        cadastrarBut.setBackground(new java.awt.Color(2,31,54));
    }//GEN-LAST:event_cadastrarButMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aba;
    private javax.swing.JLabel addAluno;
    private javax.swing.JLabel addAtividades;
    private javax.swing.JLabel addTurma1;
    private javax.swing.JPanel atividades;
    private javax.swing.JPanel atividadesBut;
    private javax.swing.JLabel bemVinda;
    private javax.swing.JPanel cadastrar;
    private javax.swing.JPanel cadastrarBut;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homeBut;
    private javax.swing.JLabel homeTxt;
    private javax.swing.JLabel homeTxt1;
    private javax.swing.JLabel homeTxt2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
