/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.telasInternas;
import javax.swing.JDesktopPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Alicea
 */
public class AtividadeDadosAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form AtividadeDadosAluno
     */
    public AtividadeDadosAluno() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nomeAluno = new javax.swing.JTextField();
        iconeEscola = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        nomeEscola = new javax.swing.JTextField();
        nomeTurma = new javax.swing.JTextField();
        texto2 = new javax.swing.JLabel();
        porcentagemNãoEntregue = new javax.swing.JTextField();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        porcentagemEntregueAtrasado = new javax.swing.JTextField();
        texto6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 217, 217));
        setMaximumSize(new java.awt.Dimension(1280, 730));
        setMinimumSize(new java.awt.Dimension(1280, 730));
        setPreferredSize(new java.awt.Dimension(1280, 730));

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 730));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 730));
        jPanel1.setPreferredSize(new java.awt.Dimension(1276, 694));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 93, 117), 1, true));
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 730));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 730));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 730));

        nomeAluno.setBackground(new java.awt.Color(236, 236, 236));
        nomeAluno.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        nomeAluno.setForeground(new java.awt.Color(239, 131, 84));
        nomeAluno.setText("Emília Luisa Garcia");
        nomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAlunoActionPerformed(evt);
            }
        });

        iconeEscola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escola.png"))); // NOI18N

        texto1.setBackground(new java.awt.Color(236, 236, 236));
        texto1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        texto1.setText("Escola:");

        nomeEscola.setBackground(new java.awt.Color(236, 236, 236));
        nomeEscola.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nomeEscola.setText("Ana Herondina");

        nomeTurma.setBackground(new java.awt.Color(236, 236, 236));
        nomeTurma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeTurma.setForeground(new java.awt.Color(4, 210, 130));
        nomeTurma.setText("6º A");
        nomeTurma.setToolTipText("");

        texto2.setBackground(new java.awt.Color(236, 236, 236));
        texto2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        texto2.setForeground(new java.awt.Color(79, 93, 117));
        texto2.setText("Não entregou: ");

        porcentagemNãoEntregue.setBackground(new java.awt.Color(236, 236, 236));
        porcentagemNãoEntregue.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        porcentagemNãoEntregue.setForeground(new java.awt.Color(204, 0, 0));
        porcentagemNãoEntregue.setText("80% ");

        texto4.setBackground(new java.awt.Color(236, 236, 236));
        texto4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        texto4.setForeground(new java.awt.Color(79, 93, 117));
        texto4.setText("das atividades");

        texto5.setBackground(new java.awt.Color(236, 236, 236));
        texto5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        texto5.setForeground(new java.awt.Color(79, 93, 117));
        texto5.setText("Entregou: ");

        porcentagemEntregueAtrasado.setEditable(false);
        porcentagemEntregueAtrasado.setBackground(new java.awt.Color(236, 236, 236));
        porcentagemEntregueAtrasado.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        porcentagemEntregueAtrasado.setForeground(new java.awt.Color(79, 93, 117));
        porcentagemEntregueAtrasado.setText("10%");

        texto6.setBackground(new java.awt.Color(236, 236, 236));
        texto6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        texto6.setForeground(new java.awt.Color(79, 93, 117));
        texto6.setText("atrasadas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(iconeEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(texto5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porcentagemEntregueAtrasado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(texto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porcentagemNãoEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconeEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(texto1)
                                .addComponent(nomeEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto2)
                    .addComponent(porcentagemNãoEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto4))
                .addGap(265, 265, 265)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto5)
                    .addComponent(porcentagemEntregueAtrasado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconeEscola;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeAluno;
    private javax.swing.JTextField nomeEscola;
    private javax.swing.JTextField nomeTurma;
    private javax.swing.JTextField porcentagemEntregueAtrasado;
    private javax.swing.JTextField porcentagemNãoEntregue;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    // End of variables declaration//GEN-END:variables
}
