/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.telasInternas;

import GUI.popup.PopupConfirmCadastAtiv;
import GUI.swing.RedmensionadorImagens;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JFormattedTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.text.MaskFormatter;

import dao.AtividadesDao;
import dao.TurmaDao;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.Atividades;
import modelo.Turma;

/**
 *
 * @author joice
 */
public class AtividadesCadastradas extends javax.swing.JInternalFrame {

    /**
     * Creates new form AtividadesCadastradas
     */
    private ArrayList<Turma> lista = new ArrayList<>();
    MaskFormatter mfdata;

    public AtividadesCadastradas() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        preecherComboBoxTurma();
        dataSolicitacaoBut.setIcon(RedmensionadorImagens.iconeRedemensionado(getClass().getResource("/img/calendar.png"), 20, 20));
        dataEntregaBut.setIcon(RedmensionadorImagens.iconeRedemensionado(getClass().getResource("/img/calendar.png"), 20, 20));
    }

    public JTextArea getDescAtv() {
        return descAtv;
    }

    public void setDescAtv(JTextArea descAtv) {
        this.descAtv = descAtv;
    }

    public JFormattedTextField getDiaEntrega() {
        return diaEntrega;
    }

    public void setDiaEntrega(JFormattedTextField diaEntrega) {
        this.diaEntrega = diaEntrega;
    }

    public JFormattedTextField getDiaSolicitado() {
        return diaSolicitado;
    }

    public void setDiaSolicitado(JFormattedTextField diaSolicitado) {
        this.diaSolicitado = diaSolicitado;
    }

    public JTextField getTipoAtv() {
        return tipoAtv;
    }

    public void setTipoAtv(JTextField tipoAtv) {
        this.tipoAtv = tipoAtv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new GUI.datechooser.DateChooser();
        dateChooser2 = new GUI.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipoAtv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descAtv = new javax.swing.JTextArea();
        diaSolicitado = new javax.swing.JFormattedTextField(mfdata);
        diaEntrega = new javax.swing.JFormattedTextField(mfdata);
        dataSolicitacaoBut = new GUI.swing.MyButton();
        dataEntregaBut = new GUI.swing.MyButton();
        jButton1 = new GUI.swing.MyButton();

        dateChooser1.setForeground(new java.awt.Color(0, 0, 255));
        dateChooser1.setTextRefernce(diaSolicitado);

        dateChooser2.setForeground(new java.awt.Color(0, 0, 255));
        dateChooser2.setTextRefernce(diaEntrega);

        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1018, 638));

        jPanel1.setBackground(new java.awt.Color(246, 246, 249));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(114, 133, 165), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 210, 130));
        jLabel1.setText("Cadastrar Atividades:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Turma:");

        jComboBox1.setLightWeightPopupEnabled(false);
        jComboBox1.setMaximumSize(new java.awt.Dimension(72, 25));
        jComboBox1.setMinimumSize(new java.awt.Dimension(72, 25));
        jComboBox1.setPreferredSize(new java.awt.Dimension(72, 25));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Data da Solicitação:");

        tipoAtv.setMaximumSize(new java.awt.Dimension(64, 25));
        tipoAtv.setMinimumSize(new java.awt.Dimension(64, 25));
        tipoAtv.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Dia:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Data de Entrega:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Dia:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Descrição:");

        descAtv.setColumns(20);
        descAtv.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        descAtv.setRows(5);
        descAtv.setText("Pronto, Danilo");
        jScrollPane1.setViewportView(descAtv);

        try {
            diaSolicitado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        diaSolicitado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diaSolicitado.setMaximumSize(new java.awt.Dimension(72, 25));
        diaSolicitado.setMinimumSize(new java.awt.Dimension(72, 25));
        diaSolicitado.setPreferredSize(new java.awt.Dimension(72, 25));
        diaSolicitado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                diaSolicitadoFocusLost(evt);
            }
        });
        diaSolicitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaSolicitadoActionPerformed(evt);
            }
        });

        try {
            diaEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        diaEntrega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        diaEntrega.setMaximumSize(new java.awt.Dimension(72, 25));
        diaEntrega.setMinimumSize(new java.awt.Dimension(72, 25));
        diaEntrega.setPreferredSize(new java.awt.Dimension(72, 25));
        diaEntrega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                diaEntregaFocusLost(evt);
            }
        });
        diaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaEntregaActionPerformed(evt);
            }
        });

        dataSolicitacaoBut.setBorderColor(new java.awt.Color(246, 246, 249));
        dataSolicitacaoBut.setColor(new java.awt.Color(246, 246, 249));
        dataSolicitacaoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSolicitacaoButActionPerformed(evt);
            }
        });

        dataEntregaBut.setBorderColor(new java.awt.Color(246, 246, 249));
        dataEntregaBut.setColor(new java.awt.Color(246, 246, 249));
        dataEntregaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataEntregaButActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(2, 30, 54));
        jButton1.setText("Cadastrar");
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(157, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(157, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(157, 40));
        jButton1.setRadius(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataSolicitacaoBut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(diaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataEntregaBut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(diaSolicitado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(75, 75, 75))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel1)
                    .addGap(187, 187, 187)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tipoAtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dataSolicitacaoBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaSolicitado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataEntregaBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(diaEntrega, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void diaSolicitadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaSolicitadoFocusLost
        // impede que o valor antigo da data que o usuario digitou volte:
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {
            Date date = sdf.parse(diaSolicitado.getText());
            diaSolicitado.setValue(sdf.format(date));
        } catch (ParseException e) {
            diaSolicitado.setFocusLostBehavior(JFormattedTextField.PERSIST);
            diaSolicitado.setText("");
            diaSolicitado.setValue(null);

        }

    }//GEN-LAST:event_diaSolicitadoFocusLost

    private void diaSolicitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaSolicitadoActionPerformed
        // TODO add your handling code here:
        dateChooser1.showPopup();      
    }//GEN-LAST:event_diaSolicitadoActionPerformed

    private void diaEntregaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaEntregaFocusLost
        // impede que o valor antigo da data que o usuario digitou volte:
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {
            Date date = sdf.parse(diaEntrega.getText());
            diaEntrega.setValue(sdf.format(date));
        } catch (ParseException e) {
            diaEntrega.setFocusLostBehavior(JFormattedTextField.PERSIST);
            diaEntrega.setText("");
            diaEntrega.setValue(null);

        }
    }//GEN-LAST:event_diaEntregaFocusLost

    private void diaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaEntregaActionPerformed
        // TODO add your handling code here:
        dateChooser2.showPopup();
    }//GEN-LAST:event_diaEntregaActionPerformed

    private void dataSolicitacaoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSolicitacaoButActionPerformed
        // TODO add your handling code here:
        dateChooser1.showPopup(); 
    }//GEN-LAST:event_dataSolicitacaoButActionPerformed

    private void dataEntregaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataEntregaButActionPerformed
        // TODO add your handling code here:
        dateChooser2.showPopup();
    }//GEN-LAST:event_dataEntregaButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Atividades atividade = new Atividades();
        int id = jComboBox1.getSelectedIndex();
        Turma turma = this.lista.get(id);
        atividade.setTipo(tipoAtv.getText());
        atividade.setDescricao(descAtv.getText());
        atividade.setTurma_id_turma(turma.getId_turma());
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            java.util.Date dataEntrega = df.parse(diaEntrega.getText());
            java.util.Date dataSolicitacao = df.parse(diaSolicitado.getText());
            java.sql.Date sqlDate = new java.sql.Date(dataEntrega.getTime());
            java.sql.Date sqlDate2 = new java.sql.Date(dataSolicitacao.getTime());
            atividade.setData_inicio(sqlDate2);
            atividade.setData_fim(sqlDate);

            PopupConfirmCadastAtiv popup = new PopupConfirmCadastAtiv(atividade, AtividadesCadastradas.this, turma.getNome());
            popup.setVisible(true);

        } catch (ParseException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.swing.MyButton dataEntregaBut;
    private GUI.swing.MyButton dataSolicitacaoBut;
    private GUI.datechooser.DateChooser dateChooser1;
    private GUI.datechooser.DateChooser dateChooser2;
    private javax.swing.JTextArea descAtv;
    private javax.swing.JFormattedTextField diaEntrega;
    private javax.swing.JFormattedTextField diaSolicitado;
    private GUI.swing.MyButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tipoAtv;
    // End of variables declaration//GEN-END:variables
    public void preecherComboBoxTurma() {
        TurmaDao turmaDao = new TurmaDao();
        lista = turmaDao.getTurma();
        for (Turma turma : lista) {
            jComboBox1.addItem("Turma: " + turma.getNome() + " - Escola: " + turma.getNome_escola());
        }
    }

}
