/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.telasInternas;

import GUI.componentes.CheckBoxContainer;
import GUI.swing.ScrollBarCustom;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JLayeredPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modelo.Aluno_Atividade;
import modelo.Atividades;

/**
 *
 * @author Lima
 */
public class AtribuirAtividadeEntregue extends javax.swing.JInternalFrame {

    private ArrayList<Aluno_Atividade> aluno;
    
    public void preencherlinhas(){
        for(Aluno_Atividade b:aluno){
            if(!b.getAluno_Ativadade_entrega()){
            CheckBoxContainer c = new CheckBoxContainer(b.getAluno(), b.getAtividade().getId_atividade());
            jLayeredPane1.add(c);
            }
        }
    }
    
    public AtribuirAtividadeEntregue(ArrayList<Aluno_Atividade> a, Atividades atividade, JDesktopPane jDesktopPane , JDesktopPane jDesktopPanePrincipal ) {
        initComponents();
        
        setBackground(new Color(246,246,249));
        myButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                for (int i = 0; i < jLayeredPane1.getComponentCount(); i++) {
                CheckBoxContainer checkBoxContainer = (CheckBoxContainer) jLayeredPane1.getComponent(i);
                checkBoxContainer.alterarSelecionados();
                }
                jDesktopPane.removeAll();
                jDesktopPane.add(new VisuAtivDadosAlunosPendentes(atividade, jDesktopPane, jDesktopPanePrincipal)).setVisible(true);
            }
        });
        this.aluno = a;
        preencherlinhas();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(-10,0,-10,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setUnitIncrement(20);
        sp.setForeground(new Color(4, 210, 130));
        jScrollPane1.setVerticalScrollBar(sp);

            
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        myButton1 = new GUI.swing.MyButton();

        setBackground(new java.awt.Color(246, 246, 249));
        setMaximumSize(new java.awt.Dimension(740, 240));
        setMinimumSize(new java.awt.Dimension(740, 240));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(740, 240));

        jPanel1.setBackground(new java.awt.Color(246, 246, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(246, 246, 249));

        jLayeredPane1.setBackground(new java.awt.Color(246, 246, 249));
        jLayeredPane1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        jScrollPane1.setViewportView(jLayeredPane1);

        myButton1.setForeground(new java.awt.Color(2, 30, 54));
        myButton1.setText("Salvar e Sair");
        myButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        myButton1.setMaximumSize(new java.awt.Dimension(157, 40));
        myButton1.setMinimumSize(new java.awt.Dimension(157, 40));
        myButton1.setPreferredSize(new java.awt.Dimension(157, 40));
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.swing.MyButton myButton1;
    // End of variables declaration//GEN-END:variables

}
