/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.telasInternas;

import java.awt.Cursor;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author isaqu
 */
public class TiposDeCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form tiposDeCadastro
     */
    javax.swing.JDesktopPane jDesktopPanel;
    public TiposDeCadastro() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    
    public TiposDeCadastro(javax.swing.JDesktopPane jDesktopPanel) {
        this.jDesktopPanel = jDesktopPanel;
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAluno = new GUI.swing.MyButton();
        addTurma = new GUI.swing.MyButton();
        addAtividade = new GUI.swing.MyButton();

        setPreferredSize(new java.awt.Dimension(1018, 638));

        addAluno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addAluno.setForeground(new java.awt.Color(255, 255, 255));
        addAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plus2.png"))); // NOI18N
        addAluno.setText("Adicionar Aluno");
        addAluno.setBorderPainted(false);
        addAluno.setColorClicked(new java.awt.Color(4, 210, 130));
        addAluno.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        addAluno.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addAluno.setIconTextGap(28);
        addAluno.setPreferredSize(new java.awt.Dimension(397, 76));
        addAluno.setRadius(12);
        addAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addAlunoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addAlunoMouseExited(evt);
            }
        });
        addAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlunoActionPerformed(evt);
            }
        });

        addTurma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addTurma.setForeground(new java.awt.Color(255, 255, 255));
        addTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plus2.png"))); // NOI18N
        addTurma.setText("Adicionar Turma");
        addTurma.setBorderPainted(false);
        addTurma.setColorClicked(new java.awt.Color(4, 210, 130));
        addTurma.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        addTurma.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addTurma.setIconTextGap(28);
        addTurma.setPreferredSize(new java.awt.Dimension(397, 76));
        addTurma.setRadius(12);
        addTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addTurmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addTurmaMouseExited(evt);
            }
        });
        addTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTurmaActionPerformed(evt);
            }
        });

        addAtividade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addAtividade.setForeground(new java.awt.Color(255, 255, 255));
        addAtividade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plus2.png"))); // NOI18N
        addAtividade.setText("Adicionar Atividade");
        addAtividade.setBorderPainted(false);
        addAtividade.setColorClicked(new java.awt.Color(4, 210, 130));
        addAtividade.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        addAtividade.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addAtividade.setIconTextGap(7);
        addAtividade.setPreferredSize(new java.awt.Dimension(397, 76));
        addAtividade.setRadius(12);
        addAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addAtividadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addAtividadeMouseExited(evt);
            }
        });
        addAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addAluno, addAtividade, addTurma});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(addTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(addAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(addAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addAluno, addAtividade, addTurma});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlunoActionPerformed
         CadastrarAlunos cadastroAlunos = new CadastrarAlunos();
         jDesktopPanel.removeAll();
        jDesktopPanel.add(cadastroAlunos).setVisible(true);
    }//GEN-LAST:event_addAlunoActionPerformed

    private void addTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTurmaActionPerformed
         CadastrarTurma cadastrarTurma = new CadastrarTurma();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(cadastrarTurma).setVisible(true);
    }//GEN-LAST:event_addTurmaActionPerformed

    private void addAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAtividadeActionPerformed
         AtividadesCadastradas atividadesCadastradas = new AtividadesCadastradas();
      jDesktopPanel.removeAll();
      jDesktopPanel.add( atividadesCadastradas).setVisible(true);
    }//GEN-LAST:event_addAtividadeActionPerformed

    private void addTurmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTurmaMouseEntered
        addTurma.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addTurmaMouseEntered

    private void addTurmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTurmaMouseExited
        addTurma.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_addTurmaMouseExited

    private void addAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAlunoMouseEntered
        addAluno.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addAlunoMouseEntered

    private void addAlunoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAlunoMouseExited
        addAluno.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_addAlunoMouseExited

    private void addAtividadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAtividadeMouseEntered
        addAtividade.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addAtividadeMouseEntered

    private void addAtividadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAtividadeMouseExited
        addAtividade.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_addAtividadeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.swing.MyButton addAluno;
    private GUI.swing.MyButton addAtividade;
    private GUI.swing.MyButton addTurma;
    // End of variables declaration//GEN-END:variables
}
