/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI.telasInternas;

import GUI.card.CardAtivEntregue;
import GUI.swing.ScrollBarCustom;
import dao.Aluno_AtividadeDao;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modelo.Aluno;
import modelo.Aluno_Atividade;

/**
 *
 * @author joice
 */
public class VisualizarAtvEntregueComAtraso extends javax.swing.JInternalFrame {
      private Aluno_Atividade aluno_atividade = new Aluno_Atividade();
      private JDesktopPane jDesktopPane;
      private Aluno aluno;
     javax.swing.JDesktopPane jDesktopPanel;
     
    public VisualizarAtvEntregueComAtraso(JDesktopPane recebeCardsAtv, JDesktopPane jDesktopPanel1,Aluno aluno) {
        this.jDesktopPanel = jDesktopPanel;
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setUnitIncrement(20);
        sp.setForeground(new Color(4, 210, 130));
        jScrollPane1.setVerticalScrollBar(sp);
        this.aluno = aluno;
        preencherAtv1entregue();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     public void preencherAtv1entregue() {
        Aluno_AtividadeDao atvAluno = new Aluno_AtividadeDao();
         ArrayList<Aluno_Atividade> listaAlunoAtividade = atvAluno.buscarAtividadesDeUmAluno(aluno.getId_aluno());
        
        for (int i = 0; i < listaAlunoAtividade.size(); i++) {
            Aluno_Atividade atividade_Entregue = listaAlunoAtividade.get(i);
            if(atividade_Entregue.getAluno_Ativadade_entrega()){
                CardAtivEntregue cards = new CardAtivEntregue(atividade_Entregue, i+1); 
                jLayeredPane1.add(cards);
            }}
           
            
        }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setPreferredSize(new java.awt.Dimension(828, 275));

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        jScrollPane1.setBackground(new java.awt.Color(236, 236, 236));

        jLayeredPane1.setBackground(new java.awt.Color(236, 236, 236));
        jLayeredPane1.setLayout(new java.awt.FlowLayout());
        jScrollPane1.setViewportView(jLayeredPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
