/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.componentes;

import GUI.swing.ScrollBarCustom;
import GUI.telasInternas.AtividadeDadosAluno;
import dao.Aluno_AtividadeDao;
import dao.TurmaDao;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

import modelo.Aluno;
import modelo.Aluno_Atividade;
import modelo.Atividades;
import modelo.Turma;

/**
 *
 * @author isaqu
 */
public class AtividadesEntreguesComAtraso extends javax.swing.JPanel {

    /**
     * Creates new form AtividadesEntreguesComAtraso
     */
    private JDesktopPane jDesktopPane;
    private int id;
    private Turma turma;
    private ArrayList<Aluno> listaAluno;
    private ArrayList<Atividades> listaAtividades;
    
    public AtividadesEntreguesComAtraso(){
        initComponents();
    }
    
    public AtividadesEntreguesComAtraso(JDesktopPane jDesktopPane, int id) {
        initComponents();
        this.jDesktopPane = jDesktopPane;
        this.id = id;
        TurmaDao turmaDao = new TurmaDao();
        turma = turmaDao.buscarPorId(id);
        turma.buscarAtividades();
        listaAluno = turma.getAlunosDaTurma();
        listaAtividades = turma.getAtividadesDaTurma();

         //Cria a scrollbar customizada vertical
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setUnitIncrement(20);
        sp.setForeground(new Color(4, 210, 130));
        jScrollPane1.setVerticalScrollBar(sp);
        
        prencherPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 30, 54));
        jLabel1.setText("Entregues Atrasados:");

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prencherPane(){
        
        
        for (Aluno aluno : listaAluno) {
            Aluno_AtividadeDao aluno_AtividadeDao = new Aluno_AtividadeDao();
            ArrayList<Aluno_Atividade> listaAluno_Atividades = aluno_AtividadeDao.buscarAtividadesEntreguesAtrasadasDeUmAluno(aluno.getId_aluno());
            if (listaAluno_Atividades.size()!=0) {
                
                JLabel jlabel = new JLabel();
                jlabel.setFont(new Font("Arial", 1 ,16));
                jlabel.setBackground(new Color(236,236,236));
                jlabel.setHorizontalAlignment(JLabel.LEFT);
                jlabel.setText(aluno.getNome());
                for (int i = jlabel.getText().length(); i < 45; i++) {
                    jlabel.setText(jlabel.getText()+" ");
                }
                boolean contador = false;
                for (Aluno_Atividade aluno_Atividade : listaAluno_Atividades) {
                    for (int i = 0; i < listaAtividades.size(); i++) {
                        Atividades atividades = listaAtividades.get(i);
                        if (atividades.getId_atividade()==aluno_Atividade.getAtividade().getId_atividade() && !contador) {
                            jlabel.setText(jlabel.getText()+ "Atividade " + (i+1));
                            contador=true;
                        }else if (atividades.getId_atividade()==aluno_Atividade.getAtividade().getId_atividade()) {
                            jlabel.setText(jlabel.getText()+ " e " + (i+1));
                        }
                    }
                }
                jlabel.setText(jlabel.getText()+"                                                                     ");
                jlabel.setPreferredSize(new Dimension(680, 25));
                jlabel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        AtividadeDadosAluno atividadeDadosAluno = new AtividadeDadosAluno(aluno, jDesktopPane);
                        jDesktopPane.removeAll();
                        jDesktopPane.add(atividadeDadosAluno).setVisible(true);
                    }
                    
                });
                
                jPanel1.add(jlabel);
            }
                
        }
    } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
