/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.popup;

import GUI.telasInternas.AtividadesCadastradas;
import dao.Aluno_AtividadeDao;
import dao.AtividadesDao;
import dao.TurmaDao;
import java.util.ArrayList;
import modelo.Aluno;
import modelo.Aluno_Atividade;
import modelo.Atividades;
import modelo.Turma;

/**
 *
 * @author Alicea
 */
public class PopupConfirmCadastAtiv extends javax.swing.JFrame {

    /**
     * Creates new form PopupConfirmCadastAtiv
     */
    public PopupConfirmCadastAtiv() {
        initComponents();
    }
    
    private Atividades atividade;
    private AtividadesCadastradas atividadesCadastradas;
    
    public PopupConfirmCadastAtiv(Atividades atividade, AtividadesCadastradas ativCadatradas, String nomeDaTurma){
        this.atividade = atividade; 
        
        this.atividadesCadastradas = ativCadatradas;
        
        initComponents();
        nomeTurma.setText(nomeDaTurma);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto1 = new javax.swing.JLabel();
        nomeTurma = new javax.swing.JTextField();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        botaoCadastrar = new GUI.swing.MyButton();
        botaoCancelar = new GUI.swing.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));
        setMinimumSize(new java.awt.Dimension(410, 173));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 246, 249));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 93, 117), 2, true));
        jPanel1.setForeground(new java.awt.Color(79, 83, 117));
        jPanel1.setMaximumSize(new java.awt.Dimension(410, 173));
        jPanel1.setMinimumSize(new java.awt.Dimension(410, 173));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 173));

        texto1.setBackground(new java.awt.Color(217, 217, 217));
        texto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texto1.setText("Tem certeza que deseja adicionar essa atividade para");

        nomeTurma.setEditable(false);
        nomeTurma.setBackground(new java.awt.Color(246, 246, 249));
        nomeTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeTurma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeTurma.setText("Turma 6 A");

        texto3.setBackground(new java.awt.Color(217, 217, 217));
        texto3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texto3.setText("?\"");

        texto4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texto4.setText("\"");

        botaoCadastrar.setForeground(new java.awt.Color(2, 30, 54));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoCadastrar.setMaximumSize(new java.awt.Dimension(117, 35));
        botaoCadastrar.setMinimumSize(new java.awt.Dimension(117, 35));
        botaoCadastrar.setPreferredSize(new java.awt.Dimension(117, 35));
        botaoCadastrar.setRadius(10);
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botaoCancelar.setForeground(new java.awt.Color(2, 30, 54));
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoCancelar.setMaximumSize(new java.awt.Dimension(117, 35));
        botaoCancelar.setMinimumSize(new java.awt.Dimension(117, 35));
        botaoCancelar.setPreferredSize(new java.awt.Dimension(117, 35));
        botaoCancelar.setRadius(10);
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(texto1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(texto4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(texto3))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(texto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto3)
                    .addComponent(texto4))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        
        AtividadesDao atividadesDao = new AtividadesDao();
        Turma turma = new TurmaDao().buscarPorId(atividade.getTurma_id_turma());
        atividadesDao.adicionar(atividade);
        atividade.puxarIdDoBanco();
        ArrayList<Aluno> listaDeAlunos = turma.getAlunosDaTurma();
        Aluno_AtividadeDao aluno_AtividadeDao = new Aluno_AtividadeDao();
        for (Aluno aluno: listaDeAlunos){
            Aluno_Atividade aluno_Atividade = new Aluno_Atividade();
            aluno_Atividade.setAluno_Ativadade_entrega(false);
            aluno_Atividade.setAluno(aluno);
            aluno_Atividade.setAtividade(atividade);
            aluno_AtividadeDao.adicionar(aluno_Atividade);
            
        }
        atividadesCadastradas.getTipoAtv().setText("");
        atividadesCadastradas.getDiaSolicitado().setText("");
        atividadesCadastradas.getDiaEntrega().setText("");
        atividadesCadastradas.getDescAtv().setText("");
        this.dispose();
        
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupConfirmCadastAtiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupConfirmCadastAtiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupConfirmCadastAtiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupConfirmCadastAtiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupConfirmCadastAtiv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.swing.MyButton botaoCadastrar;
    private GUI.swing.MyButton botaoCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeTurma;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    // End of variables declaration//GEN-END:variables
}
